### ISSUE TITLE
Change early access text on NEPS Academy and refer to GitHub for bug reports and feature requests

### ISSUE THREAD

**Issue by sebastian-lempert** [ThiNepo/NepsAcademy#3]
### Is your feature request related to a problem? Please describe.

To contact the NEPS Academy team and to submit issues like bug reports or feature requests, there is only a small hint on the website, which is hidden behind a construction site symbol in the upper right corner. From there it is possible to contact us via Discord or e-mail. It would make sense to change the text and refer to the new issue tracker on GitHub.

### Describe the solution you'd like

Change the text behind the construction site symbol in the upper right corner and refer to this new issue tracker on GitHub. Place a text like: If you have a bug or an idea, first read the FAQ (see issue #2 ) and browse the open issues before opening a new one.

People who do not speak English or whose English skills are not good enough should be encouraged to submit an English bug report or feature request by first creating their issue in their native language and then translating it into English using deepl.com. In these cases, a note could also be placed stating that deepl.com was used (e.g. `Translated with www.DeepL.com/Translator (free version)`) for the translation and that the native language is actually language X. If you consider using templates to be filled in by users (see issue #1 ) you could also integrate hints like "native language = X, used deepl.com to create this issue = Yes/No" into the templates.

### Describe alternatives you've considered

Existing alternatives are: Discord and E-Mail. Both have the disadvantage of making it difficult to follow up on an issue and continue or revisit an earlier discussion. Also, cross-referencing between different but interdependent issues is too difficult. Moreover, e-mails are only seen by those who are directly involved in the communication. Here, there is a risk that the same issue will be reported multiple times. Finally, it is recommended to use a single channel for issues in order to maintain an overview. Suggestion: Exclusively use GitHub and ask users who contact you via Discord or email to create an issue on GitHub after checking whether an issue already exists that describes the user's problem.

### Additional context

None

**Comment by ThiNepo** [comment]
Added reference to Github on the "Early Access Tooltip".
